version: '3'
services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./backups/sql:/opt/backups
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-read-only-compressed=OFF"
    env_file: .env.prod
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Europe/Paris

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.buildkit
    working_dir: /var/www/html
    env_file: .env.prod
    depends_on:
      - db
      - redis
    volumes:
      - ./app/config.php:/var/www/html/config.php
      - type: bind
        source: ${APP_SRC}
        target: /var/www/html
      - type: bind
        source: ${MOODLEDATA_SRC}
        target: /var/moodledata
    ports:
      - 9000:9000

  nginx:
    image: nginx:latest
    env_file: .env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod/moodle.template.conf:/etc/nginx/conf.d/default.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - type: bind
        source: ${APP_SRC}
        target: /var/www/html
    restart: always
    depends_on:
      - db
      - app
    command: >
      /bin/bash -c "envsubst '$$DOMAIN' 
      < /etc/nginx/conf.d/default.template 
      > /etc/nginx/conf.d/default.conf 
      && while :; do sleep 6h & wait $${!}; 
      nginx -s reload; done & nginx -g 'daemon off;'"
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local


