version: '3'
services:

  nginx:
    image: nginx:latest
    env_file: .env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certbot/certbot.template.conf:/etc/nginx/conf.d/default.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    command: /bin/bash -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    image: certbot/certbot
    env_file: .env.prod
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
